# Generated by Django 2.2.12 on 2020-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('room_id', models.AutoField(db_column='room_id', max_length=200, primary_key=True, serialize=False)),
                ('person1', models.CharField(db_column='person1', max_length=200)),
                ('person2', models.CharField(db_column='person2', max_length=200)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_num', models.AutoField(db_column='message_num', max_length=200, primary_key=True, serialize=False)),
                ('room_id', models.IntegerField(db_column='room_id')),
                ('writer', models.CharField(db_column='writer', max_length=200)),
                ('message', models.CharField(db_column='message', max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='sent_at')),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('member_id', models.CharField(db_column='member_id', max_length=200, primary_key=True, serialize=False)),
                ('pwd', models.CharField(db_column='pwd', max_length=200)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('birth', models.CharField(db_column='birth', max_length=200)),
                ('sex', models.CharField(db_column='sex', max_length=60)),
                ('animal', models.CharField(db_column='animal', max_length=300)),
                ('addr_city', models.CharField(db_column='addr_city', max_length=150)),
                ('addr_gu', models.CharField(db_column='addr_gu', max_length=100)),
                ('profile', models.IntegerField(db_column='profile')),
                ('img_url', models.CharField(db_column='img_url', max_length=100)),
            ],
            options={
                'db_table': 'pit_user',
                'managed': False,
            },
        ),
    ]
