# Generated by Django 3.0.5 on 2020-05-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('member_id', models.CharField(db_column='member_id', max_length=200, primary_key=True, serialize=False)),
                ('img_url', models.CharField(db_column='img_url', max_length=200)),
            ],
            options={
                'db_table': 'pit_img',
                'managed': False,
            },
        ),
    ]
